options{
LOOKAHEAD = 1;

}
PARSER_BEGIN(Jason)
    class Jason{
    public static void main(String[] args)
        throws ParseException, TokenMgrError{
        Jason parser = new Jason(System.in);
        parser.Start();

        }

    }
    PARSER_END(Jason)
    SKIP: {" "}
    SKIP: {"\n" | "\r" | "\r\n"}
    TOKEN: {<PLUS: "+">}
    TOKEN: {<NUM: (["0"-"9"])+>}
    void Start():
    {}
{
<NUM>
    (
    <PLUS> <NUM>

    )*
    <EOF>

}
